import { useEffect, useMemo, useRef, useState, type ReactNode } from "react";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { toPng } from "html-to-image";
import Markdown from "react-markdown";
import clsx from "clsx";
import { statusSlidesApi } from "../api/statusSlides";
import type {
  SlideSection,
  SlideTemplate,
  SlideTheme,
  StatusSlide,
  StatusSlideInput,
} from "../api/types";

type ThemePreset = {
  id: string;
  label: string;
  theme: SlideTheme;
};

const THEME_PRESETS: ThemePreset[] = [
  {
    id: "brand",
    label: "Brand Blue",
    theme: {
      preset: "brand",
      accent: "#1f45f0",
      header_bg: "#1f45f0",
      header_text: "#ffffff",
      page_bg: "#ffffff",
      card_bg: "#f8fafc",
      text: "#1a1d29",
      muted: "#64748b",
      done_accent: "#059669",
      will_accent: "#1f45f0",
      comments_accent: "#ca8a04",
    },
  },
  {
    id: "midnight",
    label: "Midnight",
    theme: {
      preset: "midnight",
      accent: "#38bdf8",
      header_bg: "#0f172a",
      header_text: "#f8fafc",
      page_bg: "#111827",
      card_bg: "#1e293b",
      text: "#e2e8f0",
      muted: "#94a3b8",
      done_accent: "#34d399",
      will_accent: "#38bdf8",
      comments_accent: "#fbbf24",
    },
  },
  {
    id: "forest",
    label: "Forest",
    theme: {
      preset: "forest",
      accent: "#047857",
      header_bg: "#065f46",
      header_text: "#ecfdf5",
      page_bg: "#f0fdf4",
      card_bg: "#ffffff",
      text: "#14532d",
      muted: "#4d7c6f",
      done_accent: "#059669",
      will_accent: "#0f766e",
      comments_accent: "#b45309",
    },
  },
  {
    id: "slate",
    label: "Slate",
    theme: {
      preset: "slate",
      accent: "#334155",
      header_bg: "#1e293b",
      header_text: "#f8fafc",
      page_bg: "#f8fafc",
      card_bg: "#ffffff",
      text: "#0f172a",
      muted: "#64748b",
      done_accent: "#0f766e",
      will_accent: "#334155",
      comments_accent: "#b45309",
    },
  },
  {
    id: "ocean",
    label: "Ocean",
    theme: {
      preset: "ocean",
      accent: "#0284c7",
      header_bg: "#0369a1",
      header_text: "#f0f9ff",
      page_bg: "#f0f9ff",
      card_bg: "#ffffff",
      text: "#0c4a6e",
      muted: "#64748b",
      done_accent: "#0d9488",
      will_accent: "#0284c7",
      comments_accent: "#c2410c",
    },
  },
];

const DEFAULT_TEMPLATE: SlideTemplate = {
  eyebrow: "Status slide",
  footer: "Generated by Executive Assistant · Insight",
  show_eyebrow: true,
  show_footer: true,
  columns: 3,
  card_style: "bordered",
  title_size: "md",
};

const SECTION_ACCENTS = ["#059669", "#1f45f0", "#ca8a04", "#db2777"];

function defaultSections(theme: SlideTheme): SlideSection[] {
  return [
    {
      id: "done",
      title: "What I've done",
      items: ["Shipped the **first cut** of the feature", "Closed outstanding `blockers`"],
      accent: theme.done_accent,
    },
    {
      id: "will",
      title: "What will be done",
      items: ["Finish remaining *polish*", "Share update with stakeholders"],
      accent: theme.will_accent,
    },
    {
      id: "comments",
      title: "Comments",
      items: ["No major risks this week — see [notes](https://example.com)"],
      accent: theme.comments_accent,
    },
  ];
}

function linesToList(value: string): string[] {
  return value
    .split("\n")
    .map((line) => line.replace(/^[-*•]\s*/, "").trimEnd())
    .filter((line) => line.trim().length > 0)
    .map((line) => line.trim());
}

function listToLines(items: string[]): string {
  return items.join("\n");
}

/** Keeps raw textarea text so Space/Enter work while typing; syncs cleaned bullets to the parent. */
function SectionItemsEditor({
  items,
  onItemsChange,
}: {
  items: string[];
  onItemsChange: (items: string[]) => void;
}) {
  const [text, setText] = useState(() => listToLines(items));

  return (
    <textarea
      value={text}
      onChange={(e) => {
        const next = e.target.value;
        setText(next);
        onItemsChange(linesToList(next));
      }}
      onBlur={() => {
        // Normalize only after editing finishes so trailing spaces/newlines don't fight the caret.
        const cleaned = linesToList(text);
        setText(listToLines(cleaned));
        onItemsChange(cleaned);
      }}
      rows={4}
      placeholder={"One bullet per line. Markdown supported:\n**bold** *italic* `code` [link](url)"}
      className="mb-2 w-full rounded-md border border-slate-300 px-2 py-1.5 font-mono text-sm"
    />
  );
}

function emptyDraft(): StatusSlideInput {
  const theme = THEME_PRESETS[0].theme;
  return {
    title: "Weekly Status",
    period_label: "Week of " + new Date().toLocaleDateString(undefined, { month: "short", day: "numeric" }),
    author: "",
    sections: defaultSections(theme),
    template: { ...DEFAULT_TEMPLATE },
    theme,
    notes: null,
  };
}

function ensureSections(slide: StatusSlide): SlideSection[] {
  if (slide.sections?.length) {
    return slide.sections.map((section, index) => ({
      id: section.id || `section-${index + 1}`,
      title: section.title || `Section ${index + 1}`,
      items: section.items ?? [],
      accent: section.accent || SECTION_ACCENTS[index % SECTION_ACCENTS.length],
    }));
  }
  const theme = { ...THEME_PRESETS[0].theme, ...slide.theme };
  return [
    { id: "done", title: "What I've done", items: slide.done_items ?? [], accent: theme.done_accent },
    { id: "will", title: "What will be done", items: slide.will_do_items ?? [], accent: theme.will_accent },
    { id: "comments", title: "Comments", items: slide.comments ?? [], accent: theme.comments_accent },
  ];
}

export default function StatusSlideBuilder() {
  const queryClient = useQueryClient();
  const slideRef = useRef<HTMLDivElement>(null);
  const [draft, setDraft] = useState<StatusSlideInput>(emptyDraft);
  const [selectedId, setSelectedId] = useState<number | null>(null);
  const [message, setMessage] = useState<string | null>(null);
  const [error, setError] = useState<string | null>(null);
  const [busy, setBusy] = useState<"png" | "pdf" | "save" | null>(null);

  const { data: saved = [], isLoading } = useQuery({
    queryKey: ["status-slides"],
    queryFn: statusSlidesApi.list,
  });

  const invalidate = () => queryClient.invalidateQueries({ queryKey: ["status-slides"] });

  const saveMutation = useMutation({
    mutationFn: async () => {
      if (selectedId) return statusSlidesApi.update(selectedId, draft);
      return statusSlidesApi.create(draft);
    },
    onSuccess: (slide) => {
      setSelectedId(slide.id);
      setMessage(selectedId ? "Slide updated." : "Slide saved.");
      invalidate();
    },
    onError: (err: any) => setError(err?.response?.data?.detail ?? "Could not save slide."),
    onSettled: () => setBusy(null),
  });

  const deleteMutation = useMutation({
    mutationFn: (id: number) => statusSlidesApi.remove(id),
    onSuccess: () => {
      if (selectedId) {
        setSelectedId(null);
        setDraft(emptyDraft());
      }
      invalidate();
      setMessage("Slide deleted.");
    },
  });

  useEffect(() => {
    if (!message) return;
    const timer = window.setTimeout(() => setMessage(null), 2500);
    return () => window.clearTimeout(timer);
  }, [message]);

  const payload = useMemo<StatusSlideInput>(
    () => ({
      ...draft,
      title: draft.title.trim() || "Status Update",
      period_label: draft.period_label?.trim() || null,
      author: draft.author?.trim() || null,
      sections: draft.sections.slice(0, draft.template.columns),
      template: {
        ...draft.template,
        columns: Math.min(4, Math.max(1, draft.template.columns)),
      },
    }),
    [draft],
  );

  const visibleSections = payload.sections;

  function loadSlide(slide: StatusSlide) {
    setSelectedId(slide.id);
    setDraft({
      title: slide.title,
      period_label: slide.period_label,
      author: slide.author,
      sections: ensureSections(slide),
      template: { ...DEFAULT_TEMPLATE, ...(slide.template ?? {}) },
      theme: { ...THEME_PRESETS[0].theme, ...slide.theme },
      notes: slide.notes,
    });
    setError(null);
  }

  function applyPreset(preset: ThemePreset) {
    setDraft((prev) => ({
      ...prev,
      theme: { ...preset.theme },
      sections: prev.sections.map((section, index) => ({
        ...section,
        accent:
          index === 0
            ? preset.theme.done_accent
            : index === 1
              ? preset.theme.will_accent
              : index === 2
                ? preset.theme.comments_accent
                : section.accent,
      })),
    }));
  }

  function updateTheme(patch: Partial<SlideTheme>) {
    setDraft((prev) => ({
      ...prev,
      theme: { ...prev.theme, ...patch, preset: "custom" },
    }));
  }

  function updateTemplate(patch: Partial<SlideTemplate>) {
    setDraft((prev) => {
      const nextTemplate = { ...prev.template, ...patch };
      let sections = prev.sections;
      if (typeof patch.columns === "number" && patch.columns > sections.length) {
        const extras = Array.from({ length: patch.columns - sections.length }, (_, i) => ({
          id: `section-${Date.now()}-${i}`,
          title: `Section ${sections.length + i + 1}`,
          items: [] as string[],
          accent: SECTION_ACCENTS[(sections.length + i) % SECTION_ACCENTS.length],
        }));
        sections = [...sections, ...extras];
      }
      if (typeof patch.columns === "number" && patch.columns < sections.length) {
        sections = sections.slice(0, patch.columns);
      }
      return { ...prev, template: nextTemplate, sections };
    });
  }

  function updateSection(id: string, patch: Partial<SlideSection>) {
    setDraft((prev) => ({
      ...prev,
      sections: prev.sections.map((section) => (section.id === id ? { ...section, ...patch } : section)),
    }));
  }

  function moveSection(id: string, direction: -1 | 1) {
    setDraft((prev) => {
      const index = prev.sections.findIndex((section) => section.id === id);
      const target = index + direction;
      if (index < 0 || target < 0 || target >= prev.sections.length) return prev;
      const next = [...prev.sections];
      const [item] = next.splice(index, 1);
      next.splice(target, 0, item);
      return { ...prev, sections: next };
    });
  }

  function removeSection(id: string) {
    setDraft((prev) => {
      if (prev.sections.length <= 1) return prev;
      const sections = prev.sections.filter((section) => section.id !== id);
      return {
        ...prev,
        sections,
        template: { ...prev.template, columns: sections.length },
      };
    });
  }

  function addSection() {
    setDraft((prev) => {
      if (prev.sections.length >= 4) return prev;
      const sections = [
        ...prev.sections,
        {
          id: `section-${Date.now()}`,
          title: `Section ${prev.sections.length + 1}`,
          items: [],
          accent: SECTION_ACCENTS[prev.sections.length % SECTION_ACCENTS.length],
        },
      ];
      return {
        ...prev,
        sections,
        template: { ...prev.template, columns: sections.length },
      };
    });
  }

  async function exportPng() {
    if (!slideRef.current) return;
    setBusy("png");
    setError(null);
    try {
      const dataUrl = await toPng(slideRef.current, {
        cacheBust: true,
        pixelRatio: 2,
        backgroundColor: draft.theme.page_bg,
      });
      const link = document.createElement("a");
      link.download = `${slugify(payload.title)}.png`;
      link.href = dataUrl;
      link.click();
      setMessage("PNG exported.");
    } catch (err) {
      setError(err instanceof Error ? err.message : "Could not export PNG.");
    } finally {
      setBusy(null);
    }
  }

  async function exportPdf() {
    setBusy("pdf");
    setError(null);
    try {
      if (selectedId) {
        await statusSlidesApi.update(selectedId, payload);
        await statusSlidesApi.exportPdf(selectedId);
        await statusSlidesApi.download(selectedId, `${slugify(payload.title)}.pdf`);
        invalidate();
      } else {
        await statusSlidesApi.previewExport(payload, `${slugify(payload.title)}.pdf`);
      }
      setMessage("PDF exported.");
    } catch (err: any) {
      setError(err?.response?.data?.detail ?? "Could not export PDF.");
    } finally {
      setBusy(null);
    }
  }

  function handleSave() {
    setBusy("save");
    setError(null);
    saveMutation.mutate();
  }

  const titleClass =
    draft.template.title_size === "lg"
      ? "text-3xl"
      : draft.template.title_size === "sm"
        ? "text-xl"
        : "text-2xl";

  const gridClass =
    visibleSections.length <= 1
      ? "grid-cols-1"
      : visibleSections.length === 2
        ? "grid-cols-2"
        : visibleSections.length === 4
          ? "grid-cols-4"
          : "grid-cols-3";

  return (
    <div className="grid grid-cols-1 gap-6 xl:grid-cols-[320px_1fr]">
      <aside className="space-y-4">
        <div className="rounded-xl bg-white p-5 shadow-sm">
          <div className="mb-3 flex items-center justify-between">
            <h2 className="text-sm font-semibold text-slate-800">Saved slides</h2>
            <button
              onClick={() => {
                setSelectedId(null);
                setDraft(emptyDraft());
              }}
              className="text-xs font-semibold text-brand-600 hover:underline"
            >
              New
            </button>
          </div>
          {isLoading && <p className="text-xs text-slate-400">Loading...</p>}
          {!isLoading && saved.length === 0 && (
            <p className="text-xs text-slate-400">No saved slides yet.</p>
          )}
          <ul className="max-h-40 space-y-1 overflow-y-auto">
            {saved.map((slide) => (
              <li
                key={slide.id}
                className={clsx(
                  "flex items-center gap-1 rounded-lg",
                  selectedId === slide.id ? "bg-brand-50" : "hover:bg-slate-50",
                )}
              >
                <button
                  onClick={() => loadSlide(slide)}
                  className={clsx(
                    "min-w-0 flex-1 truncate px-3 py-2 text-left text-sm font-medium",
                    selectedId === slide.id ? "text-brand-700" : "text-slate-700",
                  )}
                >
                  {slide.title}
                </button>
                <button
                  onClick={() => deleteMutation.mutate(slide.id)}
                  className="px-2 py-2 text-[11px] font-semibold text-slate-400 hover:text-red-600"
                >
                  Delete
                </button>
              </li>
            ))}
          </ul>
        </div>

        <div className="rounded-xl bg-white p-5 shadow-sm">
          <h2 className="mb-3 text-sm font-semibold text-slate-800">Header</h2>
          <div className="space-y-3">
            <Field label="Title">
              <input
                value={draft.title}
                onChange={(e) => setDraft({ ...draft, title: e.target.value })}
                className="w-full rounded-lg border border-slate-300 px-3 py-2 text-sm"
              />
            </Field>
            <Field label="Period">
              <input
                value={draft.period_label ?? ""}
                onChange={(e) => setDraft({ ...draft, period_label: e.target.value })}
                className="w-full rounded-lg border border-slate-300 px-3 py-2 text-sm"
              />
            </Field>
            <Field label="Author">
              <input
                value={draft.author ?? ""}
                onChange={(e) => setDraft({ ...draft, author: e.target.value })}
                className="w-full rounded-lg border border-slate-300 px-3 py-2 text-sm"
              />
            </Field>
          </div>
        </div>

        <div className="rounded-xl bg-white p-5 shadow-sm">
          <div className="mb-1 flex items-center justify-between">
            <h2 className="text-sm font-semibold text-slate-800">Template sections</h2>
            <button
              onClick={addSection}
              disabled={draft.sections.length >= 4}
              className="text-xs font-semibold text-brand-600 hover:underline disabled:opacity-40"
            >
              Add section
            </button>
          </div>
          <p className="mb-3 text-[11px] text-slate-400">
            Markdown in bullets: **bold**, *italic*, `code`, [link](url)
          </p>
          <div className="space-y-4">
            {draft.sections.map((section, index) => (
              <div key={section.id} className="rounded-lg border border-slate-200 p-3">
                <div className="mb-2 flex items-center gap-2">
                  <input
                    value={section.title}
                    onChange={(e) => updateSection(section.id, { title: e.target.value })}
                    className="min-w-0 flex-1 rounded-md border border-slate-300 px-2 py-1.5 text-sm font-medium"
                  />
                  <input
                    type="color"
                    value={normalizeColor(section.accent)}
                    onChange={(e) => updateSection(section.id, { accent: e.target.value })}
                    className="h-8 w-8 cursor-pointer rounded border border-slate-200"
                    title="Section accent"
                  />
                </div>
                <SectionItemsEditor
                  key={`${selectedId ?? "new"}-${section.id}`}
                  items={section.items}
                  onItemsChange={(items) => updateSection(section.id, { items })}
                />
                <div className="flex items-center gap-2 text-[11px] font-semibold">
                  <button
                    onClick={() => moveSection(section.id, -1)}
                    disabled={index === 0}
                    className="text-slate-500 hover:text-slate-800 disabled:opacity-30"
                  >
                    Up
                  </button>
                  <button
                    onClick={() => moveSection(section.id, 1)}
                    disabled={index === draft.sections.length - 1}
                    className="text-slate-500 hover:text-slate-800 disabled:opacity-30"
                  >
                    Down
                  </button>
                  <button
                    onClick={() => removeSection(section.id)}
                    disabled={draft.sections.length <= 1}
                    className="ml-auto text-red-500 hover:text-red-700 disabled:opacity-30"
                  >
                    Remove
                  </button>
                </div>
              </div>
            ))}
          </div>
        </div>

        <div className="rounded-xl bg-white p-5 shadow-sm">
          <h2 className="mb-3 text-sm font-semibold text-slate-800">Layout</h2>
          <div className="space-y-3">
            <Field label="Columns">
              <select
                value={draft.template.columns}
                onChange={(e) => updateTemplate({ columns: Number(e.target.value) })}
                className="w-full rounded-lg border border-slate-300 px-3 py-2 text-sm"
              >
                <option value={1}>1 column</option>
                <option value={2}>2 columns</option>
                <option value={3}>3 columns</option>
                <option value={4}>4 columns</option>
              </select>
            </Field>
            <Field label="Card style">
              <select
                value={draft.template.card_style}
                onChange={(e) => updateTemplate({ card_style: e.target.value })}
                className="w-full rounded-lg border border-slate-300 px-3 py-2 text-sm"
              >
                <option value="bordered">Bordered cards</option>
                <option value="filled">Filled cards</option>
                <option value="minimal">Minimal</option>
              </select>
            </Field>
            <Field label="Title size">
              <select
                value={draft.template.title_size}
                onChange={(e) => updateTemplate({ title_size: e.target.value })}
                className="w-full rounded-lg border border-slate-300 px-3 py-2 text-sm"
              >
                <option value="sm">Small</option>
                <option value="md">Medium</option>
                <option value="lg">Large</option>
              </select>
            </Field>
            <Field label="Eyebrow label">
              <input
                value={draft.template.eyebrow}
                onChange={(e) => updateTemplate({ eyebrow: e.target.value })}
                className="w-full rounded-lg border border-slate-300 px-3 py-2 text-sm"
              />
            </Field>
            <label className="flex items-center gap-2 text-xs text-slate-600">
              <input
                type="checkbox"
                checked={draft.template.show_eyebrow}
                onChange={(e) => updateTemplate({ show_eyebrow: e.target.checked })}
              />
              Show eyebrow
            </label>
            <Field label="Footer text">
              <input
                value={draft.template.footer}
                onChange={(e) => updateTemplate({ footer: e.target.value })}
                className="w-full rounded-lg border border-slate-300 px-3 py-2 text-sm"
              />
            </Field>
            <label className="flex items-center gap-2 text-xs text-slate-600">
              <input
                type="checkbox"
                checked={draft.template.show_footer}
                onChange={(e) => updateTemplate({ show_footer: e.target.checked })}
              />
              Show footer
            </label>
          </div>
        </div>

        <div className="rounded-xl bg-white p-5 shadow-sm">
          <h2 className="mb-3 text-sm font-semibold text-slate-800">Theme</h2>
          <div className="mb-4 grid grid-cols-2 gap-2">
            {THEME_PRESETS.map((preset) => (
              <button
                key={preset.id}
                onClick={() => applyPreset(preset)}
                className={clsx(
                  "rounded-lg border px-3 py-2 text-left text-xs font-semibold",
                  draft.theme.preset === preset.id
                    ? "border-brand-500 bg-brand-50 text-brand-700"
                    : "border-slate-200 text-slate-600 hover:bg-slate-50",
                )}
              >
                <span
                  className="mb-1 block h-2 w-full rounded"
                  style={{ background: preset.theme.header_bg }}
                />
                {preset.label}
              </button>
            ))}
          </div>
          <div className="grid grid-cols-2 gap-3">
            <ColorField
              label="Header"
              value={draft.theme.header_bg}
              onChange={(value) => updateTheme({ header_bg: value, accent: value })}
            />
            <ColorField
              label="Header text"
              value={draft.theme.header_text}
              onChange={(value) => updateTheme({ header_text: value })}
            />
            <ColorField
              label="Page"
              value={draft.theme.page_bg}
              onChange={(value) => updateTheme({ page_bg: value })}
            />
            <ColorField
              label="Card"
              value={draft.theme.card_bg}
              onChange={(value) => updateTheme({ card_bg: value })}
            />
            <ColorField
              label="Text"
              value={draft.theme.text}
              onChange={(value) => updateTheme({ text: value })}
            />
            <ColorField
              label="Muted"
              value={draft.theme.muted}
              onChange={(value) => updateTheme({ muted: value })}
            />
          </div>
        </div>
      </aside>

      <div className="min-w-0 space-y-4">
        <div className="flex flex-wrap items-center justify-between gap-3">
          <div>
            <h2 className="text-sm font-semibold text-slate-800">Live preview</h2>
            <p className="text-xs text-slate-400">
              Customize section titles, layout, and colors — then export.
            </p>
          </div>
          <div className="flex flex-wrap gap-2">
            <button
              onClick={handleSave}
              disabled={busy === "save"}
              className="rounded-lg border border-slate-300 px-4 py-2 text-sm font-semibold text-slate-700 hover:bg-slate-50 disabled:opacity-60"
            >
              {busy === "save" ? "Saving..." : selectedId ? "Save changes" : "Save slide"}
            </button>
            <button
              onClick={exportPng}
              disabled={!!busy}
              className="rounded-lg border border-slate-300 px-4 py-2 text-sm font-semibold text-slate-700 hover:bg-slate-50 disabled:opacity-60"
            >
              {busy === "png" ? "Exporting..." : "Export PNG"}
            </button>
            <button
              onClick={exportPdf}
              disabled={!!busy}
              className="rounded-lg bg-brand-600 px-4 py-2 text-sm font-semibold text-white hover:bg-brand-700 disabled:opacity-60"
            >
              {busy === "pdf" ? "Exporting..." : "Export PDF"}
            </button>
          </div>
        </div>

        {message && (
          <div className="rounded-lg bg-emerald-50 px-4 py-2 text-sm text-emerald-800">{message}</div>
        )}
        {error && <div className="rounded-lg bg-red-50 px-4 py-2 text-sm text-red-700">{error}</div>}

        <div className="overflow-x-auto rounded-xl bg-slate-200/70 p-4 shadow-inner">
          <div
            ref={slideRef}
            className="mx-auto flex aspect-[11/8.5] w-full min-w-[720px] max-w-5xl flex-col overflow-hidden rounded-lg shadow-lg"
            style={{ background: draft.theme.page_bg, color: draft.theme.text }}
          >
            <header
              className="px-8 py-5"
              style={{ background: draft.theme.header_bg, color: draft.theme.header_text }}
            >
              {draft.template.show_eyebrow && draft.template.eyebrow && (
                <p className="text-[11px] font-semibold uppercase tracking-[0.16em] opacity-80">
                  {draft.template.eyebrow}
                </p>
              )}
              <h3 className={clsx("mt-1 font-semibold leading-tight", titleClass)}>{payload.title}</h3>
              <p className="mt-1 text-sm opacity-90">
                {[payload.period_label, payload.author ? `Presented by ${payload.author}` : null]
                  .filter(Boolean)
                  .join(" · ") || "One-page update"}
              </p>
            </header>

            <div className={clsx("grid flex-1 gap-4 p-5", gridClass)}>
              {visibleSections.map((section) => (
                <SlideColumn
                  key={section.id}
                  title={section.title}
                  items={section.items}
                  accent={section.accent}
                  cardBg={draft.theme.card_bg}
                  muted={draft.theme.muted}
                  cardStyle={draft.template.card_style}
                />
              ))}
            </div>

            {draft.template.show_footer && draft.template.footer && (
              <footer className="px-8 pb-4 text-[11px]" style={{ color: draft.theme.muted }}>
                {draft.template.footer}
              </footer>
            )}
          </div>
        </div>
      </div>
    </div>
  );
}

function SlideColumn({
  title,
  items,
  accent,
  cardBg,
  muted,
  cardStyle,
}: {
  title: string;
  items: string[];
  accent: string;
  cardBg: string;
  muted: string;
  cardStyle: string;
}) {
  const style =
    cardStyle === "minimal"
      ? { background: "transparent", borderColor: "transparent", borderBottom: `2px solid ${accent}` }
      : cardStyle === "filled"
        ? { background: cardBg, borderColor: "transparent" }
        : { background: cardBg, borderColor: accent };

  return (
    <section className="flex flex-col rounded-xl border-2 p-4" style={style}>
      <h4 className="mb-3 flex items-center gap-2 text-sm font-semibold">
        <span className="inline-block h-2.5 w-2.5 rounded-sm" style={{ background: accent }} />
        {title}
      </h4>
      {items.length === 0 ? (
        <p className="text-sm" style={{ color: muted }}>
          No items yet.
        </p>
      ) : (
        <ul className="space-y-2 text-sm leading-snug">
          {items.map((item, index) => (
            <li key={`${item}-${index}`} className="flex gap-2">
              <span className="shrink-0" style={{ color: accent }}>
                •
              </span>
              <div className="min-w-0 [&_a]:underline [&_code]:rounded [&_code]:bg-black/10 [&_code]:px-1 [&_code]:py-0.5 [&_code]:font-mono [&_code]:text-[12px] [&_em]:italic [&_p]:m-0 [&_strong]:font-semibold">
                <Markdown
                  components={{
                    p: ({ children }) => <span>{children}</span>,
                    a: ({ href, children }) => (
                      <a href={href} target="_blank" rel="noreferrer">
                        {children}
                      </a>
                    ),
                  }}
                >
                  {item}
                </Markdown>
              </div>
            </li>
          ))}
        </ul>
      )}
    </section>
  );
}

function Field({
  label,
  hint,
  children,
}: {
  label: string;
  hint?: string;
  children: ReactNode;
}) {
  return (
    <div>
      <div className="mb-1 flex items-baseline justify-between">
        <label className="text-xs font-medium text-slate-600">{label}</label>
        {hint && <span className="text-[10px] text-slate-400">{hint}</span>}
      </div>
      {children}
    </div>
  );
}

function ColorField({
  label,
  value,
  onChange,
}: {
  label: string;
  value: string;
  onChange: (value: string) => void;
}) {
  return (
    <label className="block text-xs text-slate-600">
      <span className="mb-1 block font-medium">{label}</span>
      <span className="flex items-center gap-2 rounded-lg border border-slate-300 px-2 py-1.5">
        <input
          type="color"
          value={normalizeColor(value)}
          onChange={(e) => onChange(e.target.value)}
          className="h-6 w-6 cursor-pointer rounded border-0 bg-transparent p-0"
        />
        <input
          value={value}
          onChange={(e) => onChange(e.target.value)}
          className="w-full bg-transparent text-xs text-slate-700 outline-none"
        />
      </span>
    </label>
  );
}

function normalizeColor(value: string) {
  return /^#([0-9a-fA-F]{3}|[0-9a-fA-F]{6})$/.test(value) ? value : "#1f45f0";
}

function slugify(value: string) {
  return (
    value
      .trim()
      .toLowerCase()
      .replace(/[^a-z0-9]+/g, "-")
      .replace(/^-|-$/g, "") || "status-slide"
  );
}
