import os
import re
import secrets
from datetime import datetime

from reportlab.lib import colors
from reportlab.lib.pagesizes import landscape, letter
from reportlab.lib.styles import ParagraphStyle, getSampleStyleSheet
from reportlab.lib.units import inch
from reportlab.platypus import Paragraph, SimpleDocTemplate, Spacer, Table, TableStyle

from app.core.config import get_settings
from app.services.markdown_inline import markdown_to_reportlab

PAGE_SIZE = landscape(letter)
_HEX = re.compile(r"^#(?:[0-9a-fA-F]{3}|[0-9a-fA-F]{6})$")

DEFAULT_THEME = {
    "preset": "brand",
    "accent": "#1f45f0",
    "header_bg": "#1f45f0",
    "header_text": "#ffffff",
    "page_bg": "#ffffff",
    "card_bg": "#f8fafc",
    "text": "#1a1d29",
    "muted": "#64748b",
    "done_accent": "#059669",
    "will_accent": "#1f45f0",
    "comments_accent": "#ca8a04",
}

DEFAULT_TEMPLATE = {
    "eyebrow": "Status slide",
    "footer": "Generated by Executive Assistant · Insight",
    "show_eyebrow": True,
    "show_footer": True,
    "columns": 3,
    "card_style": "bordered",
    "title_size": "md",
}

DEFAULT_SECTION_DEFS = [
    ("done", "What I've done", "done_accent", "#059669"),
    ("will", "What will be done", "will_accent", "#1f45f0"),
    ("comments", "Comments", "comments_accent", "#ca8a04"),
]


def normalize_theme(theme: dict | None) -> dict:
    merged = {**DEFAULT_THEME, **(theme or {})}
    for key, value in list(merged.items()):
        if key.endswith(("_bg", "_text", "_accent")) or key in {"accent", "text", "muted"}:
            if not isinstance(value, str) or not _HEX.match(value):
                merged[key] = DEFAULT_THEME.get(key, "#1a1d29")
    return merged


def normalize_template(template: dict | None) -> dict:
    merged = {**DEFAULT_TEMPLATE, **(template or {})}
    try:
        columns = int(merged.get("columns", 3))
    except (TypeError, ValueError):
        columns = 3
    merged["columns"] = max(1, min(4, columns))
    if merged.get("card_style") not in {"bordered", "filled", "minimal"}:
        merged["card_style"] = "bordered"
    if merged.get("title_size") not in {"sm", "md", "lg"}:
        merged["title_size"] = "md"
    merged["show_eyebrow"] = bool(merged.get("show_eyebrow", True))
    merged["show_footer"] = bool(merged.get("show_footer", True))
    merged["eyebrow"] = str(merged.get("eyebrow") or DEFAULT_TEMPLATE["eyebrow"])[:80]
    merged["footer"] = str(merged.get("footer") or DEFAULT_TEMPLATE["footer"])[:160]
    return merged


def _clean_items(items: list | None, limit: int = 12) -> list[str]:
    return [str(item).strip() for item in (items or []) if item and str(item).strip()][:limit]


def normalize_sections(
    sections: list | None,
    *,
    done_items: list | None = None,
    will_do_items: list | None = None,
    comments: list | None = None,
    theme: dict | None = None,
) -> list[dict]:
    theme = normalize_theme(theme)
    if sections:
        normalized = []
        for index, raw in enumerate(sections[:4]):
            if not isinstance(raw, dict):
                continue
            accent = raw.get("accent") or theme.get("accent") or "#1f45f0"
            if not isinstance(accent, str) or not _HEX.match(accent):
                accent = "#1f45f0"
            section_id = str(raw.get("id") or f"section-{index + 1}")
            title = str(raw.get("title") or f"Section {index + 1}").strip()[:80] or f"Section {index + 1}"
            normalized.append(
                {
                    "id": section_id,
                    "title": title,
                    "items": _clean_items(raw.get("items")),
                    "accent": accent,
                }
            )
        if normalized:
            return normalized

    legacy_lists = [done_items, will_do_items, comments]
    return [
        {
            "id": section_id,
            "title": title,
            "items": _clean_items(legacy_lists[index]),
            "accent": theme.get(accent_key) or fallback,
        }
        for index, (section_id, title, accent_key, fallback) in enumerate(DEFAULT_SECTION_DEFS)
    ]


def sync_legacy_fields(sections: list[dict]) -> tuple[list[str], list[str], list[str]]:
    done = sections[0]["items"] if len(sections) > 0 else []
    will = sections[1]["items"] if len(sections) > 1 else []
    comments = sections[2]["items"] if len(sections) > 2 else []
    return done, will, comments


def default_sections(theme: dict | None = None) -> list[dict]:
    return normalize_sections(None, theme=theme)


def new_section_id() -> str:
    return f"section-{secrets.token_hex(3)}"


def _hex(value: str) -> colors.Color:
    return colors.HexColor(value)


def _escape(text: str) -> str:
    return text.replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;")


def generate_status_slide_pdf(
    *,
    slide_id: int | None,
    title: str,
    period_label: str | None,
    author: str | None,
    sections: list | None = None,
    template: dict | None = None,
    done_items: list[str] | None = None,
    will_do_items: list[str] | None = None,
    comments: list[str] | None = None,
    theme: dict | None = None,
) -> tuple[str, str]:
    """Render a one-page landscape status slide. Returns (absolute_path, relative_path)."""
    settings = get_settings()
    os.makedirs(settings.reports_dir, exist_ok=True)

    theme = normalize_theme(theme)
    template = normalize_template(template)
    sections = normalize_sections(
        sections,
        done_items=done_items,
        will_do_items=will_do_items,
        comments=comments,
        theme=theme,
    )

    timestamp = datetime.utcnow().strftime("%Y%m%d%H%M%S")
    slug = f"status_slide_{slide_id or 'draft'}_{timestamp}.pdf"
    absolute_path = os.path.join(settings.reports_dir, slug)

    title_sizes = {"sm": 18, "md": 22, "lg": 26}
    title_size = title_sizes.get(template["title_size"], 22)

    base = getSampleStyleSheet()
    title_style = ParagraphStyle(
        "StatusTitle",
        parent=base["Title"],
        textColor=_hex(theme["header_text"]),
        fontSize=title_size,
        leading=title_size + 4,
        alignment=0,
    )
    meta_style = ParagraphStyle(
        "StatusMeta",
        parent=base["Normal"],
        textColor=_hex(theme["header_text"]),
        fontSize=10,
        leading=13,
    )
    eyebrow_style = ParagraphStyle(
        "StatusEyebrow",
        parent=base["Normal"],
        textColor=_hex(theme["header_text"]),
        fontSize=9,
        leading=11,
    )
    section_title = ParagraphStyle(
        "StatusSection",
        parent=base["Heading3"],
        fontSize=12,
        leading=15,
        textColor=_hex(theme["text"]),
        spaceAfter=8,
    )
    bullet_style = ParagraphStyle(
        "StatusBullet",
        parent=base["Normal"],
        fontSize=10,
        leading=14,
        textColor=_hex(theme["text"]),
        spaceAfter=5,
    )
    empty_style = ParagraphStyle(
        "StatusEmpty",
        parent=base["Normal"],
        fontSize=9.5,
        textColor=_hex(theme["muted"]),
    )
    footer_style = ParagraphStyle(
        "StatusFooter",
        parent=base["Normal"],
        fontSize=8,
        textColor=_hex(theme["muted"]),
    )

    header_bits: list = []
    if template["show_eyebrow"] and template["eyebrow"]:
        header_bits.append(Paragraph(_escape(template["eyebrow"]).upper(), eyebrow_style))
        header_bits.append(Spacer(1, 4))
    header_bits.append(Paragraph(_escape(title or "Status Update"), title_style))
    header_bits.append(Spacer(1, 4))
    meta_bits = [bit for bit in [period_label, author and f"Presented by {author}"] if bit]
    header_bits.append(
        Paragraph(
            " &nbsp;&middot;&nbsp; ".join(_escape(bit) for bit in meta_bits)
            if meta_bits
            else "One-page status slide",
            meta_style,
        )
    )

    header = Table([[header_bits]], colWidths=[PAGE_SIZE[0] - 0.7 * inch])
    header.setStyle(
        TableStyle(
            [
                ("BACKGROUND", (0, 0), (-1, -1), _hex(theme["header_bg"])),
                ("LEFTPADDING", (0, 0), (-1, -1), 18),
                ("RIGHTPADDING", (0, 0), (-1, -1), 18),
                ("TOPPADDING", (0, 0), (-1, -1), 14),
                ("BOTTOMPADDING", (0, 0), (-1, -1), 14),
            ]
        )
    )

    columns = min(template["columns"], max(1, len(sections)))
    col_width = (PAGE_SIZE[0] - 0.9 * inch) / columns
    cards = []
    for section in sections[:columns]:
        accent = section["accent"]
        body: list = [
            Paragraph(
                f'<font color="{accent}"><b>■</b></font>&nbsp;&nbsp;<b>{_escape(section["title"])}</b>',
                section_title,
            )
        ]
        if section["items"]:
            for item in section["items"]:
                body.append(Paragraph(f"• {markdown_to_reportlab(item)}", bullet_style))
        else:
            body.append(Paragraph("No items yet.", empty_style))

        card = Table([[body]], colWidths=[col_width - 8])
        style_cmds = [
            ("LEFTPADDING", (0, 0), (-1, -1), 12),
            ("RIGHTPADDING", (0, 0), (-1, -1), 12),
            ("TOPPADDING", (0, 0), (-1, -1), 12),
            ("BOTTOMPADDING", (0, 0), (-1, -1), 12),
            ("VALIGN", (0, 0), (-1, -1), "TOP"),
        ]
        if template["card_style"] == "bordered":
            style_cmds.extend(
                [
                    ("BACKGROUND", (0, 0), (-1, -1), _hex(theme["card_bg"])),
                    ("BOX", (0, 0), (-1, -1), 1.5, _hex(accent)),
                ]
            )
        elif template["card_style"] == "filled":
            style_cmds.append(("BACKGROUND", (0, 0), (-1, -1), _hex(theme["card_bg"])))
        else:
            style_cmds.append(("BACKGROUND", (0, 0), (-1, -1), colors.white))
            style_cmds.append(("LINEBELOW", (0, 0), (-1, 0), 1.2, _hex(accent)))

        card.setStyle(TableStyle(style_cmds))
        cards.append(card)

    # Pad empty cells if fewer sections than columns.
    while len(cards) < columns:
        cards.append("")

    body_table = Table([cards], colWidths=[col_width] * columns, rowHeights=[4.6 * inch])
    body_table.setStyle(
        TableStyle(
            [
                ("VALIGN", (0, 0), (-1, -1), "TOP"),
                ("LEFTPADDING", (0, 0), (-1, -1), 4),
                ("RIGHTPADDING", (0, 0), (-1, -1), 4),
                ("TOPPADDING", (0, 0), (-1, -1), 0),
                ("BOTTOMPADDING", (0, 0), (-1, -1), 0),
            ]
        )
    )

    story: list = [header, Spacer(1, 14), body_table]
    if template["show_footer"] and template["footer"]:
        story.extend([Spacer(1, 10), Paragraph(_escape(template["footer"]), footer_style)])

    doc = SimpleDocTemplate(
        absolute_path,
        pagesize=PAGE_SIZE,
        leftMargin=0.35 * inch,
        rightMargin=0.35 * inch,
        topMargin=0.35 * inch,
        bottomMargin=0.35 * inch,
        title=title or "Status Slide",
    )
    doc.build(story)
    return absolute_path, slug
