"""status slide customizable template sections

Revision ID: f8b3d02e4c15
Revises: e7a2c91f3d04
Create Date: 2026-07-26 16:50:00.000000

"""
import json
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = "f8b3d02e4c15"
down_revision: Union[str, None] = "e7a2c91f3d04"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


DEFAULT_TEMPLATE = {
    "eyebrow": "Status slide",
    "footer": "Generated by Executive Assistant · Insight",
    "show_eyebrow": True,
    "show_footer": True,
    "columns": 3,
    "card_style": "bordered",
    "title_size": "md",
}


def upgrade() -> None:
    op.add_column("status_slides", sa.Column("sections", sa.JSON(), nullable=True))
    op.add_column("status_slides", sa.Column("template", sa.JSON(), nullable=True))

    conn = op.get_bind()
    rows = conn.execute(
        sa.text("SELECT id, done_items, will_do_items, comments, theme FROM status_slides")
    ).mappings()
    for row in rows:
        theme = row["theme"] or {}
        if isinstance(theme, str):
            theme = json.loads(theme)
        done = row["done_items"] or []
        will = row["will_do_items"] or []
        comments = row["comments"] or []
        if isinstance(done, str):
            done = json.loads(done)
        if isinstance(will, str):
            will = json.loads(will)
        if isinstance(comments, str):
            comments = json.loads(comments)
        sections = [
            {
                "id": "done",
                "title": "What I've done",
                "items": done,
                "accent": theme.get("done_accent") or "#059669",
            },
            {
                "id": "will",
                "title": "What will be done",
                "items": will,
                "accent": theme.get("will_accent") or "#1f45f0",
            },
            {
                "id": "comments",
                "title": "Comments",
                "items": comments,
                "accent": theme.get("comments_accent") or "#ca8a04",
            },
        ]
        conn.execute(
            sa.text(
                "UPDATE status_slides SET sections = CAST(:sections AS json), "
                "template = CAST(:template AS json) WHERE id = :id"
            ),
            {
                "id": row["id"],
                "sections": json.dumps(sections),
                "template": json.dumps(DEFAULT_TEMPLATE),
            },
        )


def downgrade() -> None:
    op.drop_column("status_slides", "template")
    op.drop_column("status_slides", "sections")
