from datetime import datetime

from pydantic import BaseModel, ConfigDict, Field, field_validator


class SlideTheme(BaseModel):
    preset: str = "brand"
    accent: str = "#1f45f0"
    header_bg: str = "#1f45f0"
    header_text: str = "#ffffff"
    page_bg: str = "#ffffff"
    card_bg: str = "#f8fafc"
    text: str = "#1a1d29"
    muted: str = "#64748b"
    done_accent: str = "#059669"
    will_accent: str = "#1f45f0"
    comments_accent: str = "#ca8a04"


class SlideSection(BaseModel):
    id: str
    title: str = Field(min_length=1, max_length=80)
    items: list[str] = Field(default_factory=list)
    accent: str = "#1f45f0"

    @field_validator("items")
    @classmethod
    def clean_items(cls, value: list[str]) -> list[str]:
        return [item.strip() for item in value if isinstance(item, str) and item.strip()][:12]


class SlideTemplate(BaseModel):
    eyebrow: str = "Status slide"
    footer: str = "Generated by Executive Assistant · Insight"
    show_eyebrow: bool = True
    show_footer: bool = True
    columns: int = Field(default=3, ge=1, le=4)
    card_style: str = Field(default="bordered", pattern="^(bordered|filled|minimal)$")
    title_size: str = Field(default="md", pattern="^(sm|md|lg)$")


class StatusSlideBase(BaseModel):
    title: str = Field(min_length=1, max_length=255)
    period_label: str | None = None
    author: str | None = None
    sections: list[SlideSection] = Field(default_factory=list)
    template: SlideTemplate = Field(default_factory=SlideTemplate)
    # Legacy fields — accepted and used as fallback when sections is empty.
    done_items: list[str] = Field(default_factory=list)
    will_do_items: list[str] = Field(default_factory=list)
    comments: list[str] = Field(default_factory=list)
    theme: SlideTheme = Field(default_factory=SlideTheme)
    notes: str | None = None

    @field_validator("sections")
    @classmethod
    def limit_sections(cls, value: list[SlideSection]) -> list[SlideSection]:
        return value[:4]


class StatusSlideCreate(StatusSlideBase):
    pass


class StatusSlideUpdate(BaseModel):
    title: str | None = Field(default=None, min_length=1, max_length=255)
    period_label: str | None = None
    author: str | None = None
    sections: list[SlideSection] | None = None
    template: SlideTemplate | None = None
    done_items: list[str] | None = None
    will_do_items: list[str] | None = None
    comments: list[str] | None = None
    theme: SlideTheme | None = None
    notes: str | None = None


class StatusSlideOut(StatusSlideBase):
    model_config = ConfigDict(from_attributes=True)

    id: int
    pdf_path: str | None = None
    created_at: datetime
    updated_at: datetime
